<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="car_body">

    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="base_link_radius" value="0.001"/>
    <xacro:property name="car_link_radius" value="0.1"/>
    <xacro:property name="car_link_height" value="0.08"/>
    <xacro:property name="car_link_m" value="0.5"/>
    <xacro:property name="dist2ground" value="0.015"/>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <!-- body -->
    <link name="base_link">
        <visual>
            <geometry>
                <sphere radius="${base_link_radius}"/>
            </geometry>
        </visual>
    </link>

    <link name="car">
        <!-- <inertial>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial> -->
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${car_link_radius}" length="${car_link_height}"/>
            </geometry>
            <material name="car">
                <color rgba="1.0 0.0 0.0 0.5"/>
                <!-- <texture filename=""/> -->
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${car_link_radius}" length="${car_link_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${car_link_m}" r="${car_link_radius}" h="${car_link_height}"/>
    </link>

    <joint name="car2base_link" type="fixed">
        <origin xyz="0.0 0.0 ${car_link_height / 2 + dist2ground}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="car"/>
        <!-- <axis xyz="0.0 0.0 0.0"/> -->
        <!-- <limit lower="0.0" upper="0.0" effort="0.0" velocity="0.0"/> -->
    </joint>

    <gazebo reference="car">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <!-- body -->

    <!-- left & right wheels -->
    <xacro:property name="wheel_radius" value="0.0325"/>
    <xacro:property name="wheel_width" value="0.015"/>
    <xacro:property name="wheel_m" value="0.05"/>

    <xacro:macro name="add_wheel" params="name flag">
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_m}" r="${wheel_radius}" h="${wheel_width}"/>
        </link>

        <joint name="${name}2car" type="continuous">
            <parent link="car"/>
            <child link="${name}_wheel"/>
            <axis xyz="0 1 0"/>
            <origin xyz="0 ${flag * car_link_radius} ${-(car_link_height /2 + dist2ground - wheel_radius)}" rpy="0 0 0"/>
        </joint>

        <gazebo reference="${name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>

    <xacro:add_wheel name="left" flag="1"/>
    <xacro:add_wheel name="right" flag="-1"/>
    <!-- left & right wheels -->

    <!-- front & back wheels -->
    <xacro:property name="radius" value="0.0075"/>
    <xacro:property name="m" value="0.03"/>

    <xacro:macro name="add_support_wheel" params="name flag">
        <link name="${name}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${radius}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
                <geometry>
                    <sphere radius="${radius}"/>
                </geometry>
            </collision>
            <xacro:sphere_inertial_matrix m="${m}" r="${radius}"/>
        </link>

        <joint name="${name}2car" type="continuous">
            <origin xyz="${flag * (car_link_radius - radius)} 0 ${-(car_link_height / 2 + dist2ground / 2)}" rpy="0.0 0.0 0.0"/>
            <parent link="car"/>
            <child link="${name}_wheel"/>
            <axis xyz="1 1 1"/>
        </joint>

        <gazebo reference="${name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
    </xacro:macro>

    <xacro:add_support_wheel name="front" flag="1"/>
    <xacro:add_support_wheel name="back" flag="-1"/>
    <!-- front & back wheels -->

</robot>