<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="car_camera">

    <xacro:property name="camera_length" value="0.01"/>
    <xacro:property name="camera_width" value="0.025"/>
    <xacro:property name="camera_height" value="0.025"/>
    <xacro:property name="camera_x" value="0.08"/>
    <xacro:property name="camera_y" value="0.0"/>
    <xacro:property name="camera_z" value="${(car_link_height + camera_height) /2}"/>
    <xacro:property name="camera_m" value="0.01"/>

    <link name="camera">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertial_matrix m="${camera_m}" l="${camera_length}" w="${camera_width}" h="${camera_height}"/>
    </link>

    <joint name="camera2car" type="fixed">
        <origin xyz="${camera_x} ${camera_y} ${camera_z}" rpy="0.0 0.0 0.0"/>
        <parent link="car"/>
        <child link="camera"/>
    </joint>

    <gazebo reference="camera">
        <material>Gazebo/Blue</material>
    </gazebo>
</robot>