<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="car_laser">

    <xacro:property name="support_length" value="0.15"/>
    <xacro:property name="support_radius" value="0.01"/>
    <xacro:property name="support_x" value="0.0"/>
    <xacro:property name="support_y" value="0.0"/>
    <xacro:property name="support_z" value="${(car_link_height + support_length) / 2}"/>
    <xacro:property name="support_m" value="0.02"/>

    <link name="support">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
            <material name="red">
                <color rgba="1.0 0.0 0.0 0.8"/>
            </material>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${support_m}" r="${support_radius}" h="${support_length}"/>
    </link>

    <joint name="support2car" type="fixed">
        <origin xyz="${support_x} ${support_y} ${support_z}" rpy="0.0 0.0 0.0"/>
        <parent link="car"/>
        <child link="support"/>
    </joint>

    <gazebo reference="support">
        <material>Gazebo/White</material>
    </gazebo>

    <xacro:property name="laser_length" value="0.05"/>
    <xacro:property name="laser_radius" value="0.03"/>
    <xacro:property name="laser_x" value="0.0"/>
    <xacro:property name="laser_y" value="0.0"/>
    <xacro:property name="laser_z" value="${(support_length + laser_length) / 2}"/>
    <xacro:property name="laser_m" value="0.1"/>

    <link name="laser">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}"/>
    </link>

    <joint name="laser2support" type="fixed">
        <origin xyz="${laser_x} ${laser_y} ${laser_z}" rpy="0.0 0.0 0.0"/>
        <parent link="support"/>
        <child link="laser"/>
    </joint>

    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>